name: Jupyter Book Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Julia package registry
        uses: actions/cache@v2
        with:
          path: ~/.julia/registries
          key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-

      - name: Set up Python and Julia
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have a requirements.txt file
      
      - name: Register IPython env
        run: |
          ipython kernel install --user --name compendiummatura

      
      - name: Install Julia dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate(); using IJulia'

      - name: Install ImageMagick and Ghostscript
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ghostscript

      - name: Configure ImageMagick policy
        run: |
          echo "policy PDF 'read, write, execute, rasterize,  label, exif, path, write-path, filter, image' }" | sudo tee /etc/ImageMagick-6/policy.xml

      - name: Build Jupyter Book
        run: |
          jupyter-book build notebooks

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: notebooks/_build/html
