name: Jupyter Book Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python and Julia
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Cache Julia dependencies
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.9
          cache-key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml') }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have a requirements.txt file

      - name: Install Julia dependencies
        run: |
          julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.add("Conda"); Pkg.add("WebIO"); using IJulia, WebIO; WebIO.install_jupyter_nbextension(); IJulia.installkernel("Julia", "--project=@.")'

      - name: Build Jupyter Book
        run: |
          jupyter-book build notebooks

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: notebooks/_build/html
